### ISSUE TITLE
op-deployer: unrecognized 4 byte signature: 86d1a69f

### ISSUE THREAD

**Issue by TimTinkers** [ethereum-optimism/optimism#14029]
**Bug Description**

I am trying to use `op-deployer` to create an OP Stack deployment on Holesky using the most-recently released `op-contracts/v1.8.0` and `op-contracts/v1.7.0-beta.1-l2-contracts`. I understand that to do, given that Holesky is not a supported network, I must use specifiers that are not the default `tag://`.

My `.deployer/intent.toml` file looks like this:
```toml
configType = "custom"
l1ChainID = 17000
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "https://storage.googleapis.com/oplabs-contract-artifacts/artifacts-v1-0d64fe8c7239ed698014a97bc80a97b1a464f2a24db71c67b925af3e3fb544dc.tar.gz"
# This locally-built version from the v1.8.0 contracts release fails as well.
#l1ContractsLocator = "file:///root/optimism-op-contracts-v1.8.0/packages/contracts-bedrock/forge-artifacts/"
l2ContractsLocator = "file:///root/op-deployer/v1.7.0-beta.1+l2-contracts.zip"

[superchainRoles]
  proxyAdminOwner = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
  protocolVersionsOwner = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
  guardian = "0x18091E9138251b9c854dCe077C0784A529eEc16D"

[[chains]]
  id = "0x000000000000000000000000000000000000000000000000000000000000c99b" # 51611
  baseFeeVaultRecipient = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
  l1FeeVaultRecipient = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
  sequencerFeeVaultRecipient = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
  eip1559DenominatorCanyon = 50
  eip1559Denominator = 50
  eip1559Elasticity = 2
  [chains.roles]
    l1ProxyAdminOwner = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
    l2ProxyAdminOwner = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
    systemConfigOwner = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
    unsafeBlockSigner = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
    batcher = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
    proposer = "0x18091E9138251b9c854dCe077C0784A529eEc16D"
    challenger = "0x18091E9138251b9c854dCe077C0784A529eEc16D"

[globalDeployOverrides]
  gasLimit = 30000000
  l2BlockTime = 12
```

Here is what I encounter when I attempt to apply this intent with `op-deployer`. My `L1_RPC_URL` is `https://prettiest-summer-spring.ethereum-holesky.quiknode.pro` and `PRIVATE_KEY` is the private key of `0x18091E9138251b9c854dCe077C0784A529eEc16D`.

```
root@box:~/op-deployer# ./op-deployer --version
op-deployer version v0.0.0-6ce9caf1-2025-01-15T23:24:20Z-dev
root@box:~/op-deployer# ./op-deployer --log.level "TRACE" apply --workdir .deployer --l1-rpc-url $L1_RPC_URL --private-key $PRIVATE_KEY
INFO [01-28|21:12:02.429] initializing pipeline                    stage=init strategy=live
INFO [01-28|21:12:02.446] superchain deployment not needed         stage=deploy-superchain
INFO [01-28|21:12:02.447] deploying implementations                stage=deploy-implementations
DEBUG[01-28|21:12:06.994] adding precompile                        addr=0xfdAf657f7146c1AB9db4d70cEd5FDEa7dC4906c0
DEBUG[01-28|21:12:08.060] labeling                                 addr=0xfdAf657f7146c1AB9db4d70cEd5FDEa7dC4906c0 label=*opcm.DeployImplementationsInput
DEBUG[01-28|21:12:08.060] adding precompile                        addr=0x8f0818c1e0a4cA9Bc005f61428f7f8a371464D38
DEBUG[01-28|21:12:08.102] labeling                                 addr=0x8f0818c1e0a4cA9Bc005f61428f7f8a371464D38 label=*opcm.DeployImplementationsOutput
DEBUG[01-28|21:12:08.140] labeling                                 addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployImplementations
DEBUG[01-28|21:12:08.140] Allowing cheatcodes                      address=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployImplementations
DEBUG[01-28|21:12:08.197] callframe input                          depth=1 input=0xfc4dcacb000000000000000000000000fdaf657f7146c1ab9db4d70ced5fdea7dc4906c00000000000000000000000008f0818c1e0a4ca9bc005f61428f7f8a371464d38 pc=1075 op=STATICCALL
WARN [01-28|21:12:08.197] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployImplementations
WARN [01-28|21:12:08.197] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployImplementations             err="execution reverted" revertMsg="unrecognized 4 byte signature: 86d1a69f" depth=1
WARN [01-28|21:12:08.197] Fault                                    addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployImplementations             err="execution reverted" depth=1
DEBUG[01-28|21:12:08.197] callframe input                          depth=1 input=0xfc4dcacb000000000000000000000000fdaf657f7146c1ab9db4d70ced5fdea7dc4906c00000000000000000000000008f0818c1e0a4ca9bc005f61428f7f8a371464d38 pc=1093 op=REVERT
WARN [01-28|21:12:08.197] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployImplementations
WARN [01-28|21:12:08.197] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployImplementations             err="execution reverted" revertMsg="unrecognized 4 byte signature: 86d1a69f" depth=0
DEBUG[01-28|21:12:08.197] removing precompile                      addr=0x8f0818c1e0a4cA9Bc005f61428f7f8a371464D38
DEBUG[01-28|21:12:08.197] removing precompile                      addr=0xfdAf657f7146c1AB9db4d70cEd5FDEa7dC4906c0
Application failed: error in pipeline stage apply: error deploying implementations: failed to run DeployImplementations script: revert: unrecognized 4 byte signature: 86d1a69f
```

I am using `op-deployer` version `op-deployer version v0.0.0-6ce9caf1-2025-01-15T23:24:20Z-dev` which I got from the most recent `op-deployer` release on GitHub. I have set my `forge` version to `forge 0.2.0 (143abd6a7 2025-01-28T05:17:28.359055184Z)` to match the version of the v1.8.0 contract release.

As you can see, I encounter this `Application failed: error in pipeline stage apply: error deploying implementations: failed to run DeployImplementations script: revert: unrecognized 4 byte signature: 86d1a69f` error which, from exploring the OP R&D Discord server, I've tried to eliminate by matching versions and using the non-`tag://` releases.

Maybe I'm seeing this because there is no OPCM bootstrapped on Holesky? I tried to use `op-deployer bootstrap opcm --l1-rpc-url $L1_RPC_URL --private-key $PRIVATE_KEY --release op-contracts/v1.8.0` to no avail because that tag is unavailable; and I cannot even bootstrap v1.6.0 on Holesky due to being an unsupported network.

Any help would be appreciated, thank you.

**Steps to Reproduce**

Follow the `op-deployer` instructions to prepare a type-`custom` intent file for application to an unsupported network using contract tags that are not of type `tag://`. Attempt to `apply`.

**Expected behavior**

I expect to be able to deploy these contracts to my chosen network.

**Environment Information:**
Ubuntu 24.10 x86_64 
Kernel: 6.11.0-9-generic 
CPU: DO-Regular (4) @ 1.995GHz 
GPU: 00:02.0 Red Hat, Inc. Virtio 1.0 GPU 
Memory: 226MiB / 7940MiB 

op-deployer version v0.0.0-6ce9caf1-2025-01-15T23:24:20Z-dev
`forge 0.2.0 (143abd6a7 2025-01-28T05:17:28.359055184Z)`

**Comment by tynes** [comment]
Looks like the `release()` function is missing someplace: https://www.4byte.directory/signatures/?bytes4_signature=0x86d1a69f

Its possible that the version of `op-deployer` calls this and it doesn't exist on the contracts that you are using. cc @mslipper 

Maybe try a previous release of `op-deployer`

**Comment by TimTinkers** [comment]
> Looks like the `release()` function is missing someplace: https://www.4byte.directory/signatures/?bytes4_signature=0x86d1a69f
> 
> Its possible that the version of `op-deployer` calls this and it doesn't exist on the contracts that you are using. cc [@mslipper](https://github.com/mslipper)
> 
> Maybe try a previous release of `op-deployer`

Thank you! I just confirmed after tracing through everything `op-deployer` was doing that what was once `release` has been renamed to `l1ContractsRelease` https://github.com/ethereum-optimism/optimism/blob/d83cefb2cf3d244e29c0391e3adc56534476dc06/packages/contracts-bedrock/scripts/deploy/DeployImplementations.s.sol#L120 and the v1.8.0 release on GitHub still uses the `release` name. I will try to redeploy soon.

**Comment by tynes** [comment]
@maurelian why did we change the name here? we need to define the API between deployer <> solidity and freeze it. cc @mslipper

**Comment by tynes** [comment]
> > Looks like the `release()` function is missing someplace: https://www.4byte.directory/signatures/?bytes4_signature=0x86d1a69f
> > Its possible that the version of `op-deployer` calls this and it doesn't exist on the contracts that you are using. cc [@mslipper](https://github.com/mslipper)
> > Maybe try a previous release of `op-deployer`
> 
> Thank you! I just confirmed after tracing through everything `op-deployer` was doing that what was once `release` has been renamed to `l1ContractsRelease`
> 
> [optimism/packages/contracts-bedrock/scripts/deploy/DeployImplementations.s.sol](https://github.com/ethereum-optimism/optimism/blob/d83cefb2cf3d244e29c0391e3adc56534476dc06/packages/contracts-bedrock/scripts/deploy/DeployImplementations.s.sol#L120)
> 
> Line 120 in [d83cefb](/ethereum-optimism/optimism/commit/d83cefb2cf3d244e29c0391e3adc56534476dc06)
> 
>  function l1ContractsRelease() public view returns (string memory) { 
> and the v1.8.0 release on GitHub still uses the `release` name. I will try to redeploy soon.

We should consider patching over this logic in the deployer by trying to call both

**Comment by InoMurko** [comment]
Getting similar results:
```
error deploying implementations: failed to run DeployImplementations script: revert: unrecognized 4 byte signature: f5b9fe9d
```

L1ContractsLocator: artifacts.DefaultL1ContractsLocator,
		L2ContractsLocator: artifacts.DefaultL2ContractsLocator,

```
&{
  ConfigType:standard-overrides 
L1ChainID:84532 
SuperchainRoles:0x4000e84840 
FundDevAccounts:false 
UseInterop:false 
L1ContractsLocator:0x2f620b0 
L2ContractsLocator:0x2f620d0 
Chains:[&{ID:0x000000000000000000000000000000000000000000000000000000000756b5f7 
  BaseFeeVaultRecipient:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7 
  L1FeeVaultRecipient:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7 
  SequencerFeeVaultRecipient:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7 
  Eip1559DenominatorCanyon:250 
  Eip1559Denominator:50 
  Eip1559Elasticity:6 
  Roles:{L1ProxyAdminOwner:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7 
  L2ProxyAdminOwner:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7 
  SystemConfigOwner:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7 
  UnsafeBlockSigner:0x32E3ec8B074697F73DB4B73B2D470e530c6e4B2A 
  Batcher:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7 
  Proposer:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7 
  Challenger:0xE140E56BD8393E1b9B7BF9648987E65cdC3ee6f7} 
    DeployOverrides:map[
      baseFeeVaultMinimumWithdrawalAmount:0xde0b6b3a7640000 
      baseFeeVaultWithdrawalNetwork:remote 
      eip1559Denominator:250 
      enableGovernance:false 
      gasPriceOracleBaseFeeScalar:1101 
      gasPriceOracleBlobBaseFeeScalar:659851 
      l2BlockTime: 
      l2GenesisBlockGasLimit:0x1c9c380 
      sequencerFeeVaultMinimumWithdrawalAmount:0xde0b6b3a7640000 
      useFaultProofs:false] 
    DangerousAltDAConfig:{
      UseAltDA:false 
      DACommitmentType: 
      DAChallengeWindow:0 
      DAResolveWindow:0 
      DABondSize:0 
      DAResolverRefundPercentage:0} 
      AdditionalDisputeGames:[]}
  ] 
GlobalDeployOverrides:map[]}
```

DeploymentTarget:   deployer.DeploymentTargetGenesis,
st := &state.State{
		Version: 1,
	}

**Comment by remiehneppo** [comment]
I got the same error to: 

> Application failed: error in pipeline stage apply: error deploying OP chain: failed to run DeployOPChain.s.sol script: revert: unrecognized 4 byte signature: 470f50dc


I have run a fork of Sepolia on local by hardhat.
My intent.toml:
>configType= "standard"
l1ChainID = 11155111
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "tag://op-contracts/v1.8.0-rc.4"
l2ContractsLocator = "tag://op-contracts/v1.7.0-beta.1+l2-contracts"
[superchainRoles]
  proxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
  protocolVersionsOwner = "0xfd1d2e729ae8eee2e146c033bf4400fe75284301"
  guardian = "0x7a50f00e8d05b95f98fe38d8bee366a7324dcf7e"
[[chains]]
  id = "0x00000000000000000000000000000000000000000000000000000000069f6bc7"
  baseFeeVaultRecipient = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  l1FeeVaultRecipient = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  sequencerFeeVaultRecipient = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  [chains.roles]
    l1ProxyAdminOwner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    l2ProxyAdminOwner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    systemConfigOwner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    unsafeBlockSigner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    batcher = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    proposer = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    challenger = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"


`➜  op-deployer git:(op-deployer/v0.0.12) forge -V `
>forge 0.3.0 (5a8bd89 2024-12-20T08:46:21.555250780Z)


`➜  op-deployer git:(op-deployer/v0.0.12) go version`
>go version go1.22.7 linux/amd64

**Comment by asymmetric** [comment]
It looks like the name change happened in [this PR](https://github.com/ethereum-optimism/optimism/pull/12851/files#diff-e59c74a3964f604c4a0d93915316440f2fdc55c1856e81355c9f14cc7f953d62)

**Comment by asymmetric** [comment]
For anyone else wondering how to produce the contracts tag -> artifacts URL mapping, there's a script at `packages/contracts-bedrock/scripts/ops/calculate-checksum.sh` that gives the required checksum. Requires a recursive submodule checkout.

**Comment by InoMurko** [comment]
> For anyone else wondering how to produce the contracts tag -> artifacts URL mapping, there's a script at `packages/contracts-bedrock/scripts/ops/calculate-checksum.sh` that gives the required checksum. Requires a recursive submodule checkout.

are you running a fork of `ethereum-optimism/optimism` where you've fixed this? we could just lean on your contribution.

**Comment by mslipper** [comment]
Hey folks. I'll put the bottom line upfront: **it's not possible right now to deploy past tagged releases on new chains using `op-deployer`.** We'll be fixing this in our next protocol upgrade for new versions. I know this sucks, and we're working on resolving it. For now, the workaround are:

- Deploy the tip of develop for development chains
- Use Sepolia or Mainnet, which have the correct OPCM contracts predeployed.

## Why is this?

Our contract versions currently work like this:

- We tag a release, like `op-contracts/v1.8.0`.
- We update the [release notes](https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.8.0) to reference which contracts are updated in that release.
- We manually deploy the updated contract implementations.
- We manually deploy a new OPCM to reference the newly-deployed implementations, as well as existing implementations for any any contracts that have not been updated.

There's a flaw in this strategy, however. The release only "includes" the contracts that explicitly changed during that release. This means that any contract not referenced as "updated" in the release notes is "in-development," and has not been audited or approved by governance. Deploying all contracts from the release tag will therefore deploy a combination of updated, and in-development, code. To get the version of the contract that will actually run in prod, you have to reference previous releases until you find the one where the contract in question was last updated.

As an example, to deploy on Holesky you will need to deploy contracts from versions v1.8.0, v1.6.0, and v1.4.0. On Sepolia/mainnet, we've been incrementally deploying implementation contracts so we just use those.

## How will this change in the future?

Starting with our next protocol upgrade, we will re-release all contracts when we cut the contracts version. This way you can deploy straight from the tag on any chain with no issues. We will also re-release all contracts with all new contracts versions going forward.

**Comment by Guan21** [comment]
@remiehneppo 
I got the same error too.

https://github.com/ethereum-optimism/developers/discussions/734

I think I made a mistake in modifying it. It seems that's not the case.

**Comment by jsvisa** [comment]
After checking with `git bisect`, seems the `unrecognized 4 byte signature` issue arose after https://github.com/ethereum-optimism/optimism/pull/13700

**Comment by aymentrosh** [comment]
I'm facing the same issue trying to deploy to sepolia with op-deployer 
my `intent.toml`
```
configType = "standard"
l1ChainID = 11155111
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "tag://op-contracts/v1.8.0-rc.4"
l2ContractsLocator = "tag://op-contracts/v1.7.0-beta.1+l2-contracts"

[superchainRoles]
  proxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
  protocolVersionsOwner = "0xfd1d2e729ae8eee2e146c033bf4400fe75284301"
  guardian = "0x7a50f00e8d05b95f98fe38d8bee366a7324dcf7e"

[[chains]]
  id = "0x000000000000000000000000000000000000000000000000000000000000a455"
  baseFeeVaultRecipient = "0xBbc14106079300C005cC491eD5d7ddFcD47D9B2e"
  l1FeeVaultRecipient = "0xBbc14106079300C005cC491eD5d7ddFcD47D9B2e"
  sequencerFeeVaultRecipient = "0xBbc14106079300C005cC491eD5d7ddFcD47D9B2e"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  [chains.roles]
    l1ProxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
    l2ProxyAdminOwner = "0xBbc14106079300C005cC491eD5d7ddFcD47D9B2e"
    systemConfigOwner = "0xBbc14106079300C005cC491eD5d7ddFcD47D9B2e"
    unsafeBlockSigner = "0xBbc14106079300C005cC491eD5d7ddFcD47D9B2e"
    batcher = "0xBbc14106079300C005cC491eD5d7ddFcD47D9B2e"
    proposer = "0xBbc14106079300C005cC491eD5d7ddFcD47D9B2e"
    challenger = "0xfd1d2e729ae8eee2e146c033bf4400fe75284301"
```
the `logs`
```
INFO [03-13|14:36:12.172] Initialized path database                readonly=true cache=0.00B buffer=0.00B history=0
INFO [03-13|14:36:12.173] initializing pipeline                    stage=init strategy=live
INFO [03-13|14:36:12.557] superchain deployment not needed         stage=deploy-superchain
INFO [03-13|14:36:12.559] implementations deployment not needed    stage=deploy-implementations
INFO [03-13|14:36:12.560] deploying OP chain using local allocs    stage=deploy-opchain id=0x000000000000000000000000000000000000000000000000000000000000a455
WARN [03-13|14:37:15.652] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployOPChain
WARN [03-13|14:37:15.652] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" revertMsg="unrecognized 4 byte signature: 470f50dc" depth=1
WARN [03-13|14:37:15.652] Fault                                    addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" depth=1
WARN [03-13|14:37:15.652] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployOPChain
WARN [03-13|14:37:15.652] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployOPChain err="execution reverted" revertMsg="unrecognized 4 byte signature: 470f50dc" depth=0
Application failed: error in pipeline stage apply: error deploying OP chain: failed to run DeployOPChain.s.sol script: revert: unrecognized 4 byte signature: 470f50dc
```

**Comment by seromenho** [comment]
I'm facing a similar issue here: 
https://github.com/ethereum-optimism/developers/discussions/763#discussioncomment-12523836

**Comment by bitwiseguy** [comment]
@aymentrosh @seromenho 

The latest version of deployer that is compatible with `op-contracts/v1.8.0` is `op-deployer/v0.0.14`. I was able to deploy a new  standard op-chain to sepolia using the following sequence:
```
# From monorepo
> git checkout op-deployer/v0.0.14
> cd op-deployer
> go run ./cmd/op-deployer init --l2-chain-ids=336 --workdir=.deployer
```
Then I populated the intent file with the following contents:
```
configType = "standard"
l1ChainID = 11155111
fundDevAccounts = false
useInterop = false
l1ContractsLocator = "tag://op-contracts/v1.8.0-rc.4"
l2ContractsLocator = "tag://op-contracts/v1.7.0-beta.1+l2-contracts"

[superchainRoles]
  proxyAdminOwner = "0x1eb2ffc903729a0f03966b917003800b145f56e2"
  protocolVersionsOwner = "0x79add5713b383daa0a138d3c4780c7a1804a8090"
  guardian = "0x7a50f00e8d05b95f98fe38d8bee366a7324dcf7e"

[[chains]]
  id = "0x0000000000000000000000000000000000000000000000000000000000000150"
  baseFeeVaultRecipient = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
  l1FeeVaultRecipient = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
  sequencerFeeVaultRecipient = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  [chains.roles]
    l1ProxyAdminOwner = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
    l2ProxyAdminOwner = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
    systemConfigOwner = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
    unsafeBlockSigner = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
    batcher = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
    proposer = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
    challenger = "0x83D4eB702690413a0A1E5819ECc48b62160dFb42"
```
Then I deployed the chain:
```
> go run ./cmd/op-deployer apply \                                    
  --private-key=$OP_DEPLOYER_PRIVATE_KEY \
  --l1-rpc-url $SEPOLIA_RPC_URL \
  --workdir ./.deployer
```

Does using that combination of op-deployer/op-contracts solve your issues? Let me know if not and I can try to dive deeper. This is the latest mapping of op-contracts version to op-deployer version in case you want to try other combinations:
```
op-contracts/v1.8.0 -> op-deployer/v0.0.14
op-contracts/v2.0.0 -> op-deployer/v0.2.4
op-contracts/v3.0.0 -> op-deployer/v0.3.3
```

**Comment by eshaan7** [comment]
@bitwiseguy; I have been facing this `unrecognized 4 byte signature` error when trying to deploy `op-contracts/v1.8.0` implementations to a non-standard settlement chain like Base / Base Sepolia.

These are the exact steps I followed:
- Deployed a custom superchain on Base Sepolia by checking out to `op-deployer/v0.3.2` and making some changes to `op-deployer/pkg/deployer/standard/standard.go`
- Then checkout to `op-deployer/v0.0.14` and add my superchain and other config to `op-deployer/pkg/deployer/standard/standard.go`
- Building the op-deployer binary and executing the following command:
```bash
./op-deployer bootstrap implementations \
  --artifacts-locator="tag://op-contracts/v1.8.0-rc.4" \
  --l1-contracts-release="op-contracts/v1.8.0-rc.4" \
  --l1-rpc-url="<base_sepolia_rpc>" \
  --outfile="./bootstrap_implementations_basesepolia_v180.json" \
  --private-key="<eoa_pk>" \
  --mips-version="1" \
  --protocol-versions-proxy="<custom_protocol_versions_proxy>" \
  --superchain-config-proxy="<custom_superchain_config_proxy>" 
```
- Which ends up failing with these logs:
```
INFO [07-10|17:27:58.346] artifacts download progress              current=512 total=51,778,275
INFO [07-10|17:27:59.354] artifacts download progress              current=244,507 total=51,778,275
INFO [07-10|17:28:00.354] artifacts download progress              current=4,601,657 total=51,778,275
INFO [07-10|17:28:01.355] artifacts download progress              current=19,804,163 total=51,778,275
INFO [07-10|17:28:02.356] artifacts download progress              current=34,691,873 total=51,778,275
INFO [07-10|17:28:03.358] artifacts download progress              current=49,730,571 total=51,778,275
INFO [07-10|17:28:05.036] Initialized path database                readonly=true cache=0.00B buffer=0.00B history=0
WARN [07-10|17:28:08.978] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployImplementations
WARN [07-10|17:28:08.978] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployImplementations err="execution reverted" revertMsg="unrecognized 4 byte signature: f5b9fe9d" depth=1
WARN [07-10|17:28:08.978] Fault                                    addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployImplementations err="execution reverted" depth=1
WARN [07-10|17:28:08.978] callframe                                depth=1 byte4=0xfc4dcacb addr=0x551618101B3999B61c266b9B3f8489195d32a328 callsite= label=DeployImplementations
WARN [07-10|17:28:08.978] Revert                                   addr=0x551618101B3999B61c266b9B3f8489195d32a328 label=DeployImplementations err="execution reverted" revertMsg="unrecognized 4 byte signature: f5b9fe9d" depth=0
Application failed: failed to deploy implementations: error deploying implementations: failed to run DeployImplementations script: revert: unrecognized 4 byte signature: f5b9fe9d
```

My one guess is it may have something to do with the blueprint contracts not being available on these non-standard chains.

**Comment by bitwiseguy** [comment]
@eshaan7 - you should use the same version of `op-deployer` for `bootstrap superchain`, `bootstrap implementations` and `apply` commands. So if you use `op-deployer/v0.3.3` (recommended over `op-deployer/v0.3.2`) for `bootstrap superchain`, then stay on that version, make your modifications as needed to op-deployer source code, and use `tag://op-contracts/v3.0.0` as your artifact-locator throughout the commands. Let me know if you still run into issues after trying that.

**Comment by eshaan7** [comment]
@bitwiseguy - I was already able to deploy `op-contracts/v2.0.0` and `op-contracts/v3.0.0` by using their respective op-deployer versions but it still fails for `op-contracts/v1.8.0`.

This is everything I tried:
- Previously I added Base Sepolia Chain ID and my Superchain config to `op-deployer/pkg/deployer/standard/standard.go` on top of commit 3614064c8b19ec6957d34de72f497f1d2f603245 but there when I execute `bootstrap implementations`, I get the `unrecognized 4 byte signature` error.
- On `op-deployer/v0.0.14`, the `bootstrap implementations` command is [not implemented](https://github.com/ethereum-optimism/optimism/blob/12862e7be07e733df831c44e7081863694d3caa7/op-deployer/pkg/deployer/bootstrap/flags.go#L316) and when I tried with `bootstrap opcm` then at first I got this error:
```bash
INFO [07-24|12:45:45.919] deploying OPCM                           l1ContractsRelease=op-contracts/v1.8.0-rc.4
Application failed: failed to deploy OPCM: error creating OPCM input: error getting OPCM blueprints: unsupported chain ID: 84532
```
- Deployed a new Superchain with `bootstrap superchain` and made changes in `standard.go` to support this chain ID and somehow even managed to find the blueprint contracts (by searching with bytecode on Etherscan) and added them to `standard.go` like:
```
		// Got these from Etherscan similar contracts feature
		BaseSepolia: &OPCMBlueprints{
			AddressManager:           common.HexToAddress("0x1bBf1CCE06e57501937E02C63aE8ca8e18F51D42"),
			Proxy:                    common.HexToAddress("0x213D039B6715ea1baeE7419C4971de49eb09871A"),
			ProxyAdmin:               common.HexToAddress("0x1b34cf4A497513F0ADdfa9353443C3B2573D662d"),
			L1ChugSplashProxy:        common.HexToAddress("0x478e4002768cc1B741509E8afE040fB5fdeE2E91"),
			ResolvedDelegateProxy:    common.HexToAddress("0x43aBA4d24Cc4b1664686d2a2425eC39670109E25"),
			AnchorStateRegistry:      common.HexToAddress("0x1003b08861E701f307e713C525A930C206AF8396"),
			PermissionedDisputeGame1: common.HexToAddress(""), // fixme
			PermissionedDisputeGame2: common.HexToAddress("0x182a0ad9f13370115Feb4C1F8455F6D670877101"),
		},
```
- Now when I run `bootstrap opcm` again, it does deploy an OPCM contract at [`0x8498df0b53919107bb1732864d69d70e3fb76ea9`](https://sepolia.basescan.org/address/0x8498df0b53919107bb1732864d69d70e3fb76ea9) but if you inspect the `implementations` variable of this deployed OPCM it points to addresses where there is no code so it's faulty.

Therefore, to re-iterate the issue is specific to deploying `op-contracts/v1.8.0` contract impls on a chain which is not Ethereum/Sepolia. Matthew's [comment](https://github.com/ethereum-optimism/optimism/issues/14029#issuecomment-2672316182) seems to be the reason.

It'd be quite helpful if you can try deploying a fresh superchain and v1.8.0 impls on Base Sepolia and see if you run into the same errors.

**Comment by bitwiseguy** [comment]
@eshaan7 - I can try deploying v1.8.0 impls on Base Sepolia but I think you have correctly pointed out the issues. I'm curious, since you are deploying a new superchain, any particular reason why you are trying to deploy old versions of the contracts? It seems like you'd want to start a new superchain with the latest contracts release (`op-contracts/v4.0.0`), or maybe one major release older than latest (`op-contracts/v3.0.0`).

**Comment by eshaan7** [comment]
@bitwiseguy - the reason I need `v1.8.0` impls is because I have some existing OP chains on Base and Base Sepolia on `op-contracts/v1.3.0` + L2OO. I want to upgrade it to `v3.0.0` but for that, I first need to upgrade it to `v1.8.0` + activate FPM before I can use the OPCM/op-deployer for upgrading to `v2.0.0` and `v3.0.0`.

**Comment by bitwiseguy** [comment]
@eshaan7 - I'm looking into this now. Will test deployments of `v1.8.0` contracts to base sepolia and once we get that working will push fixes into op-deployer and publish a new release (likely will be `op-deployer/v0.0.15`)

**Comment by bitwiseguy** [comment]
Closing this issue since @eshaan7 was able to implement some custom work-arounds to upgrade from `op-contracts/v1.8.0` on their chains. 

Most users are on more recent versions of `op-deployer/op-contracts` which should not have similar issues. However, if anyone else runs into similar issues, please open a new issue, or (even better) reach out to me on slack/discord by tagging `@sam_stokes` and I will help look into it.
